#
#	Makefile for this SNAP example
#	- modify Makefile.ex when creating a new SNAP example
#
#	implements:
#		all (default), clean
#

include snap/Makefile.config
include Makefile.ex
include snap/examples/Makefile.exmain
